<!--ページ共通のCSS-->
<link rel="apple-touch-icon" href="/form/common/img/apple-touch-icon.png" />
<link rel="shortcut icon" href="/form/common/img/apple-touch-icon.png" />
<link rel="stylesheet" href="/form/common/css/base.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/form/common/css/header.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/form/common/css/sidenav.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/form/common/css/form.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/form/common/css/footer.css" type="text/css" media="screen" />
<link href="/form/common/css/jquery.bxslider.css" rel="stylesheet" type="text/css" media="all">
<link href="/form/common/css/colorbox.css" rel="stylesheet">
<link href="//formcommon/css/lightbox.css" rel="stylesheet">
<link href="/form/common/css/common.css" rel="stylesheet">
<!--/ページ共通のCSS-->

<!-- jQuery library (served from Google) -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<!-- bxSlider Javascript file -->

<!--ページ共通のJS-->
<script src="/form/common/js/jquery-1.9.1.min.js"></script>
<script src="/form/common/js/jquery.easing.1.3.js"></script>
<script language="javascript" type="text/javascript" src="/common/js/jquery.bxslider.min.js"></script>
<script type="text/javascript" src="/form/common/js/jquery.heightLine.js"></script>
<script type="text/javascript" src="/form/common/js/fixheight.resp.js"></script>
<script type="text/javascript" src="/form/common/js/jquery.colorbox.js"></script>
<script type="text/javascript" src="/form/common/js/jquery.lightbox.js"></script>
<script type="text/javascript" src="/form/common/js/common.js"></script>
<!--/ページ共通のJS-->

