<div id="header-wrap">
    
    	<div id="header">
            <div class="frame clearfix">
                <div class="logo-area">
                    <p class="logo">
                        <img src="/common/img/logo.gif" alt="ipros">
                    </p>
                    <p class="logo-txt1">BtoB マーケティング支援サイト</p>
                </div><!--/.logo-area-->
			</div><!--/.frame-->
    	</div><!--/#header-->
        
    	<div id="sp-header">
            <p class="logo"><img src="/common/img/logo.gif" alt="ipros"></p>
    	</div><!--/#sp-header-->

</div><!--/#header-wrap-->
