<div class="other-category">
<h2 class="ttl-type2">他のカテゴリから事例を探す</h2>
<div class="clearfix">
		<div class="oc-box">
				<h3>目的・課題から探す</h3>
				<ul class="oc-list">
						<li><a href="/case/case_ninchido/"><img src="/case/img/task_img01.jpg" alt="">認知度向上</a></li>
						<li><a href="/case/case_eigyoulist/"><img src="/case/img/task_img02.jpg" alt="">営業リスト獲得</a></li>
						<li><a href="/case/case_syuukyaku/"><img src="/case/img/task_img03.jpg" alt="">サイト集客</a></li>
						<li><a href="/case/case_ikusei/"><img src="/case/img/task_img04.jpg" alt="">顧客育成</a></li>
				</ul>
		</div>
		<div class="oc-box">
				<h3>業界から探す</h3>
				<ul class="oc-list">
						<li><a href="/case/case_seizo/"><img src="/case/img/Business_img01.jpg" alt="">製造業界</a></li>
						<li><a href="/case/case_kensetsu/"><img src="/case/img/Business_img02.jpg" alt="">建設業界</a></li>
						<li><a href="/case/case_ls/"><img src="/case/img/Business_img03.jpg" alt="">医薬食品業界</a></li>
						<li><a href="/case/case_kaigai/"><img src="/case/img/Business_img04.jpg" alt="">海外販促</a></li>
				</ul>
		</div>
</div>
</div><!--/#other-category-->
