<div id="side-nav">
						
	<div class="side-ttl">
		<h2>成功事例</h2>
		<p><a href="/case/">成功事例TOPへ</a></p>
	</div>
	
	<div class="side-nav-list">
		<dl>
		<dt><a href="/case/">成功事例</a></dt>
		<dd>
			<ul>
			<li><a href="/case/case_ninchido/">認知度向上</a></li>
			<li><a href="/case/case_eigyoulist/">営業リスト獲得</a></li>
			<li><a href="/case/case_syuukyaku/">サイト集客</a></li>
			<li><a href="/case/case_ikusei/">顧客育成</a></li>
			<li><a href="/case/case_seizo/">製造業界</a></li>
			<li><a href="/case/case_kensetsu/">建設業界</a></li>
			<li><a href="/case/case_ls/">医薬食品業界</a></li>
			<li><a href="/case/case_kaigai/">海外販促</a></li>
			</ul>
		</dd>
		</dl>
	</div>

	<div class="side-contact-box">
		<p>お気軽に<br>お問い合わせください</p>
		<div class="btn">
			<ul>
			<li class="contct-btn"><a href="/dl/">資料請求・<br>お問い合わせ</a></li>
			<li class="event-btn"><a href="/seminar/">イベント・セミナー</a></li>
			</ul>
		</div>
	</div>

</div><!--/#side-nav-->
