<div class="relation-area mb0">
	  <h2 class="ttl-type2">関連コンテンツ</h2>
	<ul class="bnr-area clearfix">
		<li class="bnr-type1">
			<a href="">
				<p class="txt">イプロスの特長<span class="pc-only">と媒体情報</span>をご紹介<br><span class="ttl">イプロスとは？</span></p>
				<p class="arw"></p>
			</a>
		</li>
		<li class="bnr-type1">
			<a href="">
				<p class="txt">価格や機能詳細などをご案内<br><span class="ttl">サービス</span></p>
				<p class="arw"></p>
			</a>
		</li>
	</ul>
</div><!--/#seminar-->
