<div id="footer">
	<div class="frame clearfix">
		<div id="pagetop"><a href="#top"><img alt="" src="/common/img/pagetop.png"></a></div>
    	<div class="sitemap clearfix">
        	<h2>サイトマップ</h2>
            <div class="footer-nav clearfix">
            
            	<div class="fn-col">
            		<ul class="fnlist mb45">
                        <li class="fn-ttl"><a href="/ipros/">イプロスとは</a></li>
                        <li><a href="/ipros/ipros-seizou/">・イプロス製造業とは</a></li>
                        <li><a href="/ipros/ipros-kensetsu/">・イプロス建設業とは</a></li>
                        <li><a href="/ipros/ipros-ls/">・イプロス医薬食品技術とは</a></li>
                        <li><a href="/ipros/tda/">・TECH DIRECTORY Asiaとは</a></li>
                    </ul>
            		<ul class="fnlist">
                        <li class="fn-ttl"><a href="/service/">サービス</a></li>
                        <li><a href="/service/plan/">・イプロス会員プラン</a></li>
                        <li><a href="/service/ad/">・販促・広告プラン</a></li>
                        <li><a href="/service/merit/">・お役立ち機能</a></li>
                        <li><a href="/service/simulation/">・販売促進シミュレーション</a></li>
                    </ul>
            	</div><!--/.fn-col-->
            	<div class="fn-col">
            		<ul class="fnlist">
                        <li class="fn-ttl"><a href="/case/">成功事例</a></li>
                        <li><a href="/case/case_ninchido/">・認知度向上</a></li>
                        <li><a href="/case/case_eigyoulist/">・営業リスト獲得</a></li>
                        <li><a href="/case/case_syuukyaku/">・サイト集客</a></li>
                        <li><a href="/case/case_ikusei/">・顧客育成</a></li>
                        <li><a href="/case/case_seizo/">・製造業界</a></li>
                        <li><a href="/case/case_kensetsu/">・建設業界</a></li>
                        <li><a href="/case/case_ls/">・医薬食品業界</a></li>
                        <li><a href="/case/case_kaigai/">・海外販促</a></li>
                    </ul>
            	</div><!--/.fn-col-->
            	<div class="fn-col last">
            		<ul class="fnlist mb15">
                        <li class="fn-ttl"><a href="/knowhow/">成功ノウハウ</a></li>
                        <li><a href="/knowhow/attracting/">・展示会集客</a></li>
                        <li><a href="/knowhow/distribute/">・カタログ配布</a></li>
                        <li><a href="/knowhow/acquire/">・営業リスト獲得</a></li>
                        <li><a href="/knowhow/web-attracting/">・サイト集客</a></li>
                        <li><a href="/knowhow/nurture/">・顧客育成</a></li>
                    </ul>
            		<ul class="fnlist">
                        <li class="fn-ttl"><a href="/seminar/">イベント・セミナー</a></li>
                    </ul>
            		<ul class="fnlist">
                        <li class="fn-ttl"><a href="/dl/">資料請求・お問い合わせ</a></li>
                    </ul>
            		<ul class="fnlist">
                        <li class="fn-ttl"><a href="/sitemap/">サイトマップ</a></li>
                    </ul>
            		<ul class="fnlist">
                        <li class="fn-ttl"><a href="/privacy/">プライバシーポリシー</a></li>
                    </ul>
            	</div><!--/.fn-col-->
                
            </div><!--/.footer-nav-->
        </div><!--/.sitemap-->
        
        <div class="link">
        	<h2>リンク</h2>
            <ul class="clearfix mb20">
            	<li class="fl mb10"><a href="https://www.ipros.jp/" target="_blank"><img src="/common/img/footer_link01.gif" alt=""></a></li>
            	<li class="fr mb10"><a href="https://kensetsu.ipros.jp/" target="_blank"><img src="/common/img/footer_link02.gif" alt=""></a></li>
            	<li class="fl"><a href="https://ls.ipros.jp/" target="_blank"><img src="/common/img/footer_link03.gif" alt=""></a></li>
            	<li class="fr"><a href="http://www.tech-dir.com/" target="_blank"><img src="/common/img/footer_link04.gif" alt=""></a></li>
            </ul>
            <p class="footer-logo"><a href="http://corporate.ipros.jp/" target="_blank"><img src="/common/img/footer_logo.gif" alt=""></a></p>
            <div class="sns"></div>
        </div><!--/.link-->
    </div><!--/.frame-->
    
    <div id="sp_footer">
		<div id="pagetop"><a href="#top"><img alt="" src="/common/img/pagetop.png"></a></div>
        <ul class="f-nav">
            <li><a href="" class="link1">イプロスとは</a></li>
            <li><a href="" class="link1">サービス</a></li>
            <li><a href="" class="link1">成功事例</a></li>
            <li><a href="" class="link1">成功ノウハウ</a></li>
            <li><a href="/seminar/" class="link1">イベント・セミナー</a></li>
            <li><a href="/dl/" class="link1">資料請求・お問い合わせ</a></li>
            <li><a href="" class="link2" target="_blank">よくあるご質問</a></li>
            <li><a href="/sitemap/" class="link1">サイトマップ</a></li>
            <li><a href="" class="link1">会社概要</a></li>
        </ul>
    </div>
    <div class="copy">Copyright（C）IPROS CORPORATION  All Rights Reserved.</div>
</div><!--/#footer-->

