<div id="information">
	<div class="frame">
		<h2 class="ttl-type4">お気軽にお問い合わせください</h2>
		<ul class="info-btn clearfix">
			<li class="info-box1">
				<a href="/dl/">
					<p class="info-icon"><img src="/common/img/icon_document.png" alt=""></p>
					<p>資料請求・お問い合わせ</p>
				</a>
			</li>
			<li class="info-box2">
				<a href="/seminar/">
					<p class="info-icon"><img src="/common/img/icon_event.png" alt=""></p>
					<p>イベント・セミナー</p>
				</a>
			</li>
		</ul>
	</div>
</div><!--/#information-->

