<div id="side-nav">
						
	<div class="side-ttl">
		<h2>イプロスとは</h2>
		<p><a href="/ipros/">イプロスとはTOPへ</a></p>
	</div>
	
	<div class="side-nav-list">
		<dl>
		<dt><a href="/ipros/">イプロスとは</a></dt>
		<dd>
			<ul>
			<li><a href="/ipros/ipros-seizou/">イプロス製造業とは</a></li>
			<li><a href="/ipros/ipros-kensetsu/">イプロス建設業とは</a></li>
			<li><a href="/ipros/ipros-ls/">イプロス医薬食品技術とは</a></li>
			<li><a href="/ipros/tda/">TECH DIRECTORY Asiaとは</a></li>
			</ul>
		</dd>
		</dl>
	</div>

	<div class="side-contact-box">
		<p>お気軽に<br>お問い合わせください</p>
		<div class="btn">
			<ul>
			<li class="contct-btn"><a href="/dl/">資料請求・<br>お問い合わせ</a></li>
			<li class="event-btn"><a href="/seminar/">イベント・セミナー</a></li>
			</ul>
		</div>
	</div>

</div><!--/#side-nav-->
