<div class="relation-area mb0">
	  <h2 class="ttl-type2">関連コンテンツ</h2>
	<ul class="bnr-area clearfix">
		<li class="bnr-type1">
			<a href="/service/">
				<p class="txt">価格や機能詳細などをご案内<br><span class="ttl">サービス</span></p>
				<p class="arw"></p>
			</a>
		</li>
		<li class="bnr-type1">
			<a href="/knowhow/">
				<p class="txt">サイト集客やリスト獲得など課題を解決<br><span class="ttl">成功ノウハウ</span></p>
				<p class="arw"></p>
			</a>
		</li>
	</ul>
</div><!--/#seminar-->
