<div id="side-nav">
						
	<div class="side-ttl">
		<h2>イベント・セミナー</h2>
		<p><a href="/seminar/">イベント・セミナーTOPへ</a></p>
	</div>
	
	<div class="side-nav-list">
		<dl>
		<dt><a href="/seminar/">イベント・セミナー</a></dt>
		<dd>
			<ul>
			<li><a href="#">イベントセミナー（無料）</a></li>
			<li><a href="#">イプロス大学（販促支援会員限定/無料）</a></li>
			<li><a href="#">その他</a></li>
			</ul>
		</dd>
		</dl>
	</div>

	<div class="side-contact-box">
		<p>お気軽に<br>お問い合わせください</p>
		<div class="btn">
			<ul>
			<li class="contct-btn"><a href="/dl/">資料請求・<br>お問い合わせ</a></li>
			<li class="event-btn"><a href="/seminar/">イベント・セミナー</a></li>
			</ul>
		</div>
	</div>

</div><!--/#side-nav-->
