<div class="relation-area mb0">
	  <h2 class="ttl-type2">関連コンテンツ</h2>
	<ul class="bnr-area clearfix">
		<li class="bnr-type1">
			<a href="/ipros/">
				<p class="txt">イプロスの特長をご紹介<br><span class="ttl">イプロスとは</span></p>
				<p class="arw"></p>
			</a>
		</li>
		<li class="bnr-type1">
			<a href="/case/">
				<p class="txt">イプロスで導く「成功」の糸口<br><span class="ttl">成功事例</span></p>
				<p class="arw"></p>
			</a>
		</li>
	</ul>
</div><!--/#seminar-->
